### ISSUE TITLE
LB1

### ISSUE THREAD

**Issue by Simseru** [Besbe/LimitBreak#43]
Following LB1 ???'s exist in game world. Need to be removed.

Crawlers Nest:
qm10 :: 17584481
qm11 :: 17584482
qm12 :: 1754483

Garlaige Citadel:
qm18 :: 17596841
qm19 :: 17596842
qm20 :: 47596843

Eldieme Necropolis:
qm7 :: 17576428
qm8 :: 17576427
qm9 :: 17576426

**Comment by Simseru** [comment]
LB1 started and completed through traditional means succesfully.
Just needs possible DB clean up for above phantom ??? objects.

**Comment by Besbe** [comment]
Added following entries to NPC_list query

UPDATE npc_list SET status = 2 WHERE npcid = "17584481" AND name = "qm10";
UPDATE npc_list SET status = 2 WHERE npcid = "17584482" AND name = "qm11";
UPDATE npc_list SET status = 2 WHERE npcid = "17584483" AND name = "qm12";
UPDATE npc_list SET status = 2 WHERE npcid = "17596841" AND name = "qm18";
UPDATE npc_list SET status = 2 WHERE npcid = "17596842" AND name = "qm19";
UPDATE npc_list SET status = 2 WHERE npcid = "17596843" AND name = "qm20";
UPDATE npc_list SET status = 2 WHERE npcid = "17576428" AND name = "qm7";
UPDATE npc_list SET status = 2 WHERE npcid = "17576427" AND name = "qm8";
UPDATE npc_list SET status = 2 WHERE npcid = "17576426" AND name = "qm9";
